name: Start Controller
on:
  push:
    branches: main
jobs:
  start-controller:
    name: Start Controller
    runs-on: ubuntu-latest
    outputs:
        SWEEP_URL: ${{ steps.start_controller.outputs.SWEEP_URL }}
    timeout-minutes: 4320
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - id: start_controller
      name: Run Agent
      run: |
        wandb login ${{ secrets.WANDB_API_KEY }}
        echo "SWEEP_URL=$(python start.py | tail -1)" >> $GITHUB_OUTPUT
  run-experiments:
    name: Start Experiments
    needs: start-controller
    # runs-on: [ self-hosted ]
    runs-on: ubuntu-latest
    timeout-minutes: 4320
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Agent
      run: |
        wandb login ${{ secrets.WANDB_API_KEY }}
        wandb agent ${{ needs.start-controller.outputs.SWEEP_URL }}