name: Start Controller
on:
  push:
    branches: main
jobs:
  start-controller:
    name: Start Controller
    runs-on: ubuntu-latest
    outputs:
        SWEEP_URL: ${{ steps.start_controller.outputs.SWEEP_URL }}
    timeout-minutes: 4320
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - id: start_controller
      name: Setup Controller
      run: |
        wandb login ${{ secrets.WANDB_API_KEY }}
        echo "SWEEP_URL=$(python start.py | tail -1)" >> $GITHUB_OUTPUT
  run-agent-1:
    name: Run Agent 1 
    needs: start-controller
    runs-on: [ runner-1 ]
    # runs-on: ubuntu-latest
    timeout-minutes: 4320
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Agent
      run: |
        wandb login ${{ secrets.WANDB_API_KEY }}
        wandb agent ${{ needs.start-controller.outputs.SWEEP_URL }}
  run-agent-2:
    name: Run Agent 2 
    needs: start-controller
    runs-on: [ runner-2 ]
    # runs-on: ubuntu-latest
    timeout-minutes: 4320
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Agent
      run: |
        wandb login ${{ secrets.WANDB_API_KEY }}
        wandb agent ${{ needs.start-controller.outputs.SWEEP_URL }}